services:
  db:
    container_name: pomelo-db
    build:
      context: .
      dockerfile: Dockerfile-pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pomelo-db
    ports: 
      - '5432:5432'
  
  flask:
    build: .
    depends_on:
      - db
    ports: 
      - '5000:5000'
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - FLASK_DEBUG=1
    command: uv run -- flask run --host 0.0.0.0


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: collum.freedman@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
    - db