import { ShoppingList } from "@/lib/shopping_list";

export const shoppingListDummy: ShoppingList = {
  weekStart: new Date("2024-06-10"),
  items: [
    {
      id: "1",
      name: "Apples",
      quantity: 5,
      units: "pcs",
      foodType: "Fruit",
      store: {
        id: 1,
        latitude: 37.7749,
        longitude: -122.4194,
        name: "Walmart",
        address: "123 Main St, San Francisco, CA",
      },
    },
    {
      id: "2",
      name: "Bananas",
      quantity: 6,
      units: "pcs",
      foodType: "Fruit",
      store: {
        id: 2,
        latitude: 34.0522,
        longitude: -118.2437,
        name: "Target",
        address: "456 Market St, Los Angeles, CA",
      },
    },
    {
      id: "3",
      name: "Chicken Breast",
      quantity: 2,
      units: "lbs",
      foodType: "Meat",
      store: {
        id: 3,
        latitude: 40.7128,
        longitude: -74.006,
        name: "Costco",
        address: "789 Broadway, New York, NY",
      },
    },
    {
      id: "4",
      name: "Milk",
      quantity: 1,
      units: "gallon",
      foodType: "Dairy",
      store: {
        id: 4,
        latitude: 41.8781,
        longitude: -87.6298,
        name: "Kroger",
        address: "101 State St, Chicago, IL",
      },
    },
    {
      id: "5",
      name: "Eggs",
      quantity: 12,
      units: "pcs",
      foodType: "Dairy",
      store: {
        id: 5,
        latitude: 29.7604,
        longitude: -95.3698,
        name: "H-E-B",
        address: "202 Main St, Houston, TX",
      },
    },
    {
      id: "6",
      name: "Bread",
      quantity: 1,
      units: "loaf",
      foodType: "Grain",
      store: {
        id: 6,
        latitude: 47.6062,
        longitude: -122.3321,
        name: "Safeway",
        address: "303 Pine St, Seattle, WA",
      },
    },
    {
      id: "7",
      name: "Carrots",
      quantity: 2,
      units: "lbs",
      foodType: "Vegetable",
      store: {
        id: 1,
        latitude: 37.7749,
        longitude: -122.4194,
        name: "Walmart",
        address: "123 Main St, San Francisco, CA",
      },
    },
    {
      id: "8",
      name: "Rice",
      quantity: 5,
      units: "lbs",
      foodType: "Grain",
      store: {
        id: 1,
        latitude: 37.7749,
        longitude: -122.4194,
        name: "Walmart",
        address: "123 Main St, San Francisco, CA",
      },
    },
    {
      id: "9",
      name: "Cheese",
      quantity: 1,
      units: "block",
      foodType: "Dairy",
      store: {
        id: 2,
        latitude: 34.0522,
        longitude: -118.2437,
        name: "Target",
        address: "456 Market St, Los Angeles, CA",
      },
    },
    {
      id: "10",
      name: "Tomatoes",
      quantity: 4,
      units: "pcs",
      foodType: "Vegetable",
      store: {
        id: 7,
        latitude: 42.3601,
        longitude: -71.0589,
        name: "Whole Foods",
        address: "404 Boylston St, Boston, MA",
      },
    },
  ],
};
