import { ShoppingList } from "@/lib/shopping_list";

export const shoppingListDummy: ShoppingList = {
  weekStart: new Date("2024-06-10"),
  items: [
    {
      id: "1",
      name: "Apples",
      quantity: 5,
      units: "pcs",
      foodType: "Fruit",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
    {
      id: "2",
      name: "Bananas",
      quantity: 6,
      units: "pcs",
      foodType: "Fruit",
      store: {
        id: 2,
        name: "Target",
      },
    },
    {
      id: "3",
      name: "Chicken Breast",
      quantity: 2,
      units: "lbs",
      foodType: "Meat",
      store: {
        id: 3,
        name: "Costco",
      },
    },
    {
      id: "4",
      name: "Milk",
      quantity: 1,
      units: "gallon",
      foodType: "Dairy",
      store: {
        id: 4,
        name: "Kroger",
      },
    },
    {
      id: "5",
      name: "Eggs",
      quantity: 12,
      units: "pcs",
      foodType: "Dairy",
      store: {
        id: 5,
        name: "H-E-B",
      },
    },
    {
      id: "6",
      name: "Bread",
      quantity: 1,
      units: "loaf",
      foodType: "Grain",
      store: {
        id: 6,
        name: "Safeway",
      },
    },
    {
      id: "7",
      name: "Carrots",
      quantity: 2,
      units: "lbs",
      foodType: "Vegetable",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
    {
      id: "8",
      name: "Rice",
      quantity: 5,
      units: "lbs",
      foodType: "Grain",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
    {
      id: "9",
      name: "Cheese",
      quantity: 1,
      units: "block",
      foodType: "Dairy",
      store: {
        id: 2,
        name: "Target",
      },
    },
    {
      id: "10",
      name: "Tomatoes",
      quantity: 4,
      units: "pcs",
      foodType: "Vegetable",
      store: {
        id: 7,
        name: "Whole Foods",
      },
    },
    {
      id: "11",
      name: "Orange Juice",
      quantity: 2,
      units: "bottle",
      foodType: "Beverage",
      store: {
        id: 4,
        name: "Kroger",
      },
    },
    {
      id: "12",
      name: "Spinach",
      quantity: 1,
      units: "bag",
      foodType: "Vegetable",
      store: {
        id: 7,
        name: "Whole Foods",
      },
    },
    {
      id: "13",
      name: "Yogurt",
      quantity: 6,
      units: "cup",
      foodType: "Dairy",
      store: {
        id: 5,
        name: "H-E-B",
      },
    },
    {
      id: "14",
      name: "Ground Beef",
      quantity: 3,
      units: "lbs",
      foodType: "Meat",
      store: {
        id: 3,
        name: "Costco",
      },
    },
    {
      id: "15",
      name: "Potatoes",
      quantity: 10,
      units: "pcs",
      foodType: "Vegetable",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
    {
      id: "16",
      name: "Butter",
      quantity: 2,
      units: "stick",
      foodType: "Dairy",
      store: {
        id: 2,
        name: "Target",
      },
    },
    {
      id: "17",
      name: "Pasta",
      quantity: 2,
      units: "box",
      foodType: "Grain",
      store: {
        id: 6,
        name: "Safeway",
      },
    },
    {
      id: "18",
      name: "Cereal",
      quantity: 1,
      units: "box",
      foodType: "Grain",
      store: {
        id: 4,
        name: "Kroger",
      },
    },
    {
      id: "19",
      name: "Onions",
      quantity: 3,
      units: "pcs",
      foodType: "Vegetable",
      store: {
        id: 5,
        name: "H-E-B",
      },
    },
    {
      id: "20",
      name: "Salmon",
      quantity: 2,
      units: "fillet",
      foodType: "Meat",
      store: {
        id: 3,
        name: "Costco",
      },
    },
    {
      id: "21",
      name: "Peanut Butter",
      quantity: 1,
      units: "jar",
      foodType: "Spread",
      store: {
        id: 2,
        name: "Target",
      },
    },
    {
      id: "22",
      name: "Lettuce",
      quantity: 2,
      units: "head",
      foodType: "Vegetable",
      store: {
        id: 7,
        name: "Whole Foods",
      },
    },
    {
      id: "23",
      name: "Strawberries",
      quantity: 1,
      units: "box",
      foodType: "Fruit",
      store: {
        id: 6,
        name: "Safeway",
      },
    },
    {
      id: "24",
      name: "Soda",
      quantity: 12,
      units: "can",
      foodType: "Beverage",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
    {
      id: "25",
      name: "Oats",
      quantity: 1,
      units: "bag",
      foodType: "Grain",
      store: {
        id: 4,
        name: "Kroger",
      },
    },
    // Additional 20 entries
    {
      id: "26",
      name: "Grapes",
      quantity: 2,
      units: "lbs",
      foodType: "Fruit",
      store: {
        id: 2,
        name: "Target",
      },
    },
    {
      id: "27",
      name: "Broccoli",
      quantity: 1,
      units: "head",
      foodType: "Vegetable",
      store: {
        id: 7,
        name: "Whole Foods",
      },
    },
    {
      id: "28",
      name: "Turkey Breast",
      quantity: 2,
      units: "lbs",
      foodType: "Meat",
      store: {
        id: 3,
        name: "Costco",
      },
    },
    {
      id: "29",
      name: "Almond Milk",
      quantity: 1,
      units: "carton",
      foodType: "Dairy",
      store: {
        id: 4,
        name: "Kroger",
      },
    },
    {
      id: "30",
      name: "Bagels",
      quantity: 6,
      units: "pcs",
      foodType: "Grain",
      store: {
        id: 6,
        name: "Safeway",
      },
    },
    {
      id: "31",
      name: "Celery",
      quantity: 1,
      units: "bunch",
      foodType: "Vegetable",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
    {
      id: "32",
      name: "Pork Chops",
      quantity: 4,
      units: "pcs",
      foodType: "Meat",
      store: {
        id: 3,
        name: "Costco",
      },
    },
    {
      id: "33",
      name: "Blueberries",
      quantity: 1,
      units: "box",
      foodType: "Fruit",
      store: {
        id: 6,
        name: "Safeway",
      },
    },
    {
      id: "34",
      name: "Cucumbers",
      quantity: 3,
      units: "pcs",
      foodType: "Vegetable",
      store: {
        id: 5,
        name: "H-E-B",
      },
    },
    {
      id: "35",
      name: "Honey",
      quantity: 1,
      units: "jar",
      foodType: "Spread",
      store: {
        id: 2,
        name: "Target",
      },
    },
    {
      id: "36",
      name: "Granola Bars",
      quantity: 1,
      units: "box",
      foodType: "Grain",
      store: {
        id: 4,
        name: "Kroger",
      },
    },
    {
      id: "37",
      name: "Zucchini",
      quantity: 2,
      units: "pcs",
      foodType: "Vegetable",
      store: {
        id: 7,
        name: "Whole Foods",
      },
    },
    {
      id: "38",
      name: "Shrimp",
      quantity: 1,
      units: "lb",
      foodType: "Meat",
      store: {
        id: 3,
        name: "Costco",
      },
    },
    {
      id: "39",
      name: "Mushrooms",
      quantity: 1,
      units: "box",
      foodType: "Vegetable",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
    {
      id: "40",
      name: "Maple Syrup",
      quantity: 1,
      units: "bottle",
      foodType: "Spread",
      store: {
        id: 2,
        name: "Target",
      },
    },
    {
      id: "41",
      name: "Avocados",
      quantity: 4,
      units: "pcs",
      foodType: "Fruit",
      store: {
        id: 7,
        name: "Whole Foods",
      },
    },
    {
      id: "42",
      name: "Cornflakes",
      quantity: 1,
      units: "box",
      foodType: "Grain",
      store: {
        id: 4,
        name: "Kroger",
      },
    },
    {
      id: "43",
      name: "Ham",
      quantity: 1,
      units: "lb",
      foodType: "Meat",
      store: {
        id: 3,
        name: "Costco",
      },
    },
    {
      id: "44",
      name: "Peppers",
      quantity: 3,
      units: "pcs",
      foodType: "Vegetable",
      store: {
        id: 5,
        name: "H-E-B",
      },
    },
    {
      id: "45",
      name: "Raspberries",
      quantity: 1,
      units: "box",
      foodType: "Fruit",
      store: {
        id: 6,
        name: "Safeway",
      },
    },
    {
      id: "46",
      name: "Tortillas",
      quantity: 1,
      units: "pack",
      foodType: "Grain",
      store: {
        id: 1,
        name: "Walmart",
      },
    },
  ],
};
