services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pomelo-db
    ports:
      - "5432:5432"

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8081"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
      - "8081:8081"
      - "50051:50051"
    # volumes:
    #   - weaviate_data:/var/lib/weaviate
    depends_on:
      - ollama
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_API_BASED_MODULES: "true"
      ENABLE_MODULES: "text2vec-ollama,generative-ollama"
      CLUSTER_HOSTNAME: "node1"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  embedder:
    build: ./embedder
    depends_on:
      - kafka
      - weaviate
      - ollama
    environment:
      WEAVIATE_PORT: 8081
      WEAVIATE_GRPC_PORT: 50051
    command: uv run main.py

  flask-app:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - /app/.venv
    environment:
      FLASK_DEBUG: 1
    command: uv run -- flask run --host 0.0.0.0

  flask-rag:
    build: ./rag
    depends_on:
      # - flask-app
      - weaviate
    ports:
      - "5001:5001"
    volumes:
      - ./rag:/app
      - /app/.venv
    environment:
      FLASK_DEBUG: 1
      WEAVIATE_PORT: 8081
      WEAVIATE_GRPC_PORT: 50051
    command: uv run -- python app.py

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_PROCESS_ROLES: broker, controller

  client:
    build: ./client
    depends_on:
      - flask-app
      - db
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      HOST: 0.0.0.0

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: collum.freedman@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  # weaviate_data:
  ollama:
