[project]
name = "pomelo"
version = "0.1.0"
description = "A weekly recipe and shopping organizational app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.9.9",
]
